### ISSUE TITLE
这个版本是不是不支持Azure的openai接口

### ISSUE THREAD

**Issue by soilniba** [ConnectAI-E/Feishu-OpenAI-Stream-Chatbot#14]
试了一下设置AZURE_ON好像还是读的OPENAI_KEY，是不是没有支持Azure的接口呀

**Comment by bourne7** [comment]
如果 Azure 的 GPT 接口是和 OpenAI 的接口，报文完全一样，只是 URL 改变的话，那么可以改这里的代码来做到配置：

services/chatgpt/gpt3.go:50
config.BaseURL = c.config.OpenaiApiUrl + "/v1"

这里只是有个 v1 是写死的，到时候可以将这个 v1 去掉，给个配置的默认值就行。

因此我建议你本地试一下，改一下这行代码看是否能用。因为我没有 Azure 的Key，所以没法尝试了😄
