### ISSUE TITLE
deploy on railway failed  when use repo naned https://github.com/ConnectAI-E/Feishu-OpenAI-Stream-Chatbot

### ISSUE THREAD

**Issue by CuteSmartTiger** [ConnectAI-E/Feishu-OpenAI-Stream-Chatbot#3]
`
 
==============
Using Nixpacks
==============
context: 236e4a8dc138e4f53889225cb4cf66c3
 
╔═══════ Nixpacks v1.5.1 ══════╗
║ setup      │ go_1_18         ║
║──────────────────────────────║
║ install    │ go mod download ║
║──────────────────────────────║
║ build      │ go build -o out ║
║──────────────────────────────║
║ start      │ ./out           ║
╚══════════════════════════════╝
 
 
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 2.25kB done
#1 DONE 0.0s
 
#2 [internal] load .dockerignore
#2 transferring context: 2B done
 
#2 DONE 0.0s
 
#3 [internal] load metadata for ghcr.io/railwayapp/nixpacks:ubuntu-1678752204
 
#3 DONE 0.3s
 
#4 [internal] load metadata for docker.io/library/ubuntu:jammy
 
#4 DONE 0.5s
 
 
#5 [stage-0  1/10] FROM ghcr.io/railwayapp/nixpacks:ubuntu-1678752204@sha256:fba77818e57bebd4e7a02f60d45554354d6ec5a3f7d98b4ee4f6b2a6e720191e
#5 DONE 0.0s
 
#6 [stage-1 1/5] FROM docker.io/library/ubuntu:jammy@sha256:67211c14fa74f070d27cc59d69a7fa9aeff8e28ea118ef3babc295a0428a6d21
#6 DONE 0.0s
 
#7 [internal] load build context
 
#7 transferring context: 304.56kB done
#7 DONE 0.0s
 
#8 [stage-0  2/10] WORKDIR /app/
#8 CACHED
 
#9 [stage-0 3/8] COPY .nixpacks/nixpkgs-293a28df6d7ff3dec1e61e37cc4ee6e6c0fb0847.nix .nixpacks/nixpkgs-293a28df6d7ff3dec1e61e37cc4ee6e6c0fb0847.nix
#9 CACHED
 
#10 [stage-0 4/8] RUN nix-env -if .nixpacks/nixpkgs-293a28df6d7ff3dec1e61e37cc4ee6e6c0fb0847.nix && nix-collect-garbage -d
#10 CACHED
 
#11 [stage-0 5/8] COPY . /app/.
 
#11 DONE 0.1s
 
#12 [stage-0 6/8] RUN --mount=type=cache,id=s/71cbd2f2-e015-49fb-aad3-9430cebaa627-/root/cache/go-build,target=/root/.cache/go-build go mod download
 
#12 DONE 2.2s
 
#13 [stage-0 7/8] COPY . /app/.
#13 DONE 0.0s
 
 
#14 [stage-0 8/8] RUN --mount=type=cache,id=s/71cbd2f2-e015-49fb-aad3-9430cebaa627-/root/cache/go-build,target=/root/.cache/go-build go build -o out
 
#14 DONE 11.6s
 
 
#15 [stage-1 3/5] COPY --from=0 /etc/ssl/certs /etc/ssl/certs
#15 CACHED
 
#16 [stage-1 2/5] WORKDIR /app/
#16 CACHED
 
#17 [stage-1 4/5] RUN true
#17 CACHED
 
 
#18 [stage-1 5/5] COPY --from=0 /app/ /app/
#18 DONE 0.1s
 
#19 exporting to image
#19 exporting layers
 
#19 exporting layers 0.1s done
#19 writing image sha256:e915c0ad557d45ceb7f951e05cf1fb17a36e1d12da873137d7491f62394d040e done
`

**Comment by CuteSmartTiger** [comment]
deploy log
`
2023/04/14 17:10:36 http server started: [http://localhost:80/webhook/event](http://localhost/webhook/event)
`

**Comment by BeauChan** [comment]
检查下环境变量的端口是否与容器一致

**Comment by BeauChan** [comment]
能提供完整的build log吗，还有railway状态的截图

**Comment by CuteSmartTiger** [comment]
i sovled the problem by change http_port from 9000 to 80 ,the railway health check port is 80
