### ISSUE TITLE
通过飞书访问后，代码总是提示404.

### ISSUE THREAD

**Issue by mouyong** [ConnectAI-E/Feishu-OpenAI-Stream-Chatbot#6]
能收到 event 事件，不能回消息

**Comment by mouyong** [comment]
![image](https://user-images.githubusercontent.com/10336437/232676547-653c859d-3291-416b-9ad8-b543daf31a57.png)

**Comment by Leizhenpeng** [comment]
你的服务器和openai连接并不通畅
